# Generated by Django 4.2.5 on 2023-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='flag',
            new_name='destination_image',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='image',
            new_name='flag_image',
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
