# Generated by Django 4.2.5 on 2023-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('destinations', '0002_rename_flag_destination_destination_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(related_name='destinations', to='categories.category'),
        ),
    ]
