# Generated by Django 4.2.5 on 2023-10-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destination_bucketlist_destination_visited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='created_by',
            new_name='user',
        ),
    ]
