# Generated by Django 4.2.5 on 2023-10-09 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0010_alter_destination_bucketlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='bucketlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='bucketlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='destinations', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='visited',
            field=models.ManyToManyField(blank=True, null=True, related_name='visited', to=settings.AUTH_USER_MODEL),
        ),
    ]
