# Generated by Django 4.2.5 on 2023-10-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('destinations', '0012_alter_destination_bucketlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(blank=True, default=[], related_name='destinations', to='categories.category'),
        ),
    ]
