# Generated by Django 4.2.6 on 2023-10-13 10:54

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.generics


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0017_destination_invited'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationDeleteView',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinations.destination')),
            ],
            bases=('destinations.destination', rest_framework.generics.DestroyAPIView),
        ),
    ]
