# Generated by Django 4.2.5 on 2023-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.URLField(blank=True, default='https://switzerland-tour.com/storage/media/4-ForArticles/swiss-mountains.jpg'),
        ),
    ]
