# Generated by Django 4.2.5 on 2023-10-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='background_image',
        ),
    ]
