# Generated by Django 4.2.5 on 2023-10-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/djhbqxz1j/image/upload/v1697096215/bucket-list/default-profile-image_wgsxr7.png'),
        ),
    ]
